"""Add StudyNumericalOutcome model

Revision ID: 42616aa35cf0
Revises: 81770a79dac3
Create Date: 2025-09-08 21:39:55.672372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42616aa35cf0'
down_revision = '81770a79dac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_numerical_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('outcome_name', sa.String(length=200), nullable=False),
    sa.Column('events_intervention', sa.Integer(), nullable=True),
    sa.Column('total_intervention', sa.Integer(), nullable=True),
    sa.Column('events_control', sa.Integer(), nullable=True),
    sa.Column('total_control', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_numerical_outcome')
    # ### end Alembic commands ###
